import { type AppType } from "next/app";
import { api } from "~/utils/api";
import "~/styles/globals.css";
import Header from "~/components/Header";
import Head from "next/head";

const MyApp: AppType = ({ Component, pageProps }) => {
  return <>
    <Head>
      <title>Create T3 App</title>
      <meta name="description" content="Generated by create-t3-app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Header />
    <Component {...pageProps} />;
  </>
};

export default api.withTRPC(MyApp);
